---
# Environment name for logging and identification
env: "development"

# Auth Validator environment variables
# Enable debug mode for development
debug: "true"
# Secret name for development environment
secret_name: "secret/nginx/auth-validator-dev"

# Server specific configuration
server_name: "dev-aws-ingress-validator.local"

# Enable health check in development
server_health_check: "false"
