---
# Environment name for logging and identification
env: "prod"

# Auth Validator environment variables
secret_name: "secret/nginx/auth-validator"

# NGINX Plus Configuration
# Override default to use NGINX Plus
nginx_plus: true
# Path to license key file
nginx_plus_license_key: "nginx-one.key"
# Path to license certificate file
nginx_plus_license_cert: "nginx-one.crt"
# Path to JWT token file
nginx_plus_jwt_token: "nginx-one.jwt"

# NGINX App Protect WAF settings
app_protect_policy: "policy_template_nginx_base"
app_protect_violation_mode: "blocking"

# Backend servers (production specific)
backend_servers:
  - "172.31.30.4:8080"

# Enable health check in production
server_health_check: "true"

# SSL certificate options
server_certificate_chain: "certificate_chain.crt"
server_certificate_key: "certificate_key.key"
