---
# Environment name for logging and identification
env: "staging"

# Auth Validator environment variables
secret_name: "secret/nginx/auth-validator-staging"

# Server specific configuration
server_name: "staging-aws-ingress-validator.local"

# Backend servers configuration for staging
backend_servers:
  - "localhost:8080"
  - "localhost:8081"

# Enable health check in staging
server_health_check: "true"
