---
# Environment name for logging and identification
env: "staging"

# Auth Validator environment variables
secret_name: "secret/nginx/auth-validator-staging"

# Server specific configuration
server_name: "staging-aws-ingress-validator.local"

# Backend servers configuration for staging
backend_servers:
  - "localhost:8080"
  - "localhost:8081"

# Enable health check in staging
server_health_check: "false"

nginx_plus: true
# Path to NGINX Plus license key file relative to nginx/license/<hostname>/ 
nginx_plus_license_key: "nginx-one.key"
# Path to NGINX Plus license cert file relative to nginx/license/<hostname>/
nginx_plus_license_cert: "nginx-one.crt"
# Path to NGINX Plus JWT token file relative to nginx/license/<hostname>/
nginx_plus_jwt_token: "nginx-one.jwt"
