---
- name: Deploy main rsyslog configuration
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Deploy NGINX specific rsyslog configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/rsyslog.d/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Deploy App Protect specific rsyslog configuration
  ansible.builtin.template:
    src: app-protect.conf.j2
    dest: /etc/rsyslog.d/app-protect.conf
    owner: root
    group: root
    mode: '0644'
  when: nginx_plus | bool
  notify: Restart rsyslog
