---
- name: Deploy main rsyslog configuration
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Deploy NGINX specific rsyslog configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/rsyslog.d/10-nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Deploy App Protect specific rsyslog configuration
  ansible.builtin.template:
    src: app-protect.conf.j2
    dest: /etc/rsyslog.d/11-app-protect.conf
    owner: root
    group: root
    mode: '0644'
  when: nginx_plus | bool
  notify: Restart rsyslog

- name: Deploy auth-validator rsyslog configuration
  ansible.builtin.template:
    src: auth-validator.conf.j2
    dest: /etc/rsyslog.d/12-auth-validator.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog
