---
- name: Deploy and configure rsyslog
  hosts: "{{ target_hosts | default(env) | default('prod') }}"
  become: true
  gather_facts: true

  pre_tasks:
    - name: Include environment-specific variables
      ansible.builtin.include_vars: "../environments/{{ env | default('prod') }}.yml"
      tags: [always]

    - name: Display selected environment
      ansible.builtin.debug:
        msg: "Deploying to {{ env | default('prod') }} environment on {{ inventory_hostname }}"
      tags: [always]

    - name: Display selected environment
      ansible.builtin.debug:
        msg: "Deploying to {{ env | default('prod') }} environment on {{ inventory_hostname }}"
      tags: [always]

    - name: Ensure rsyslog is installed
      ansible.builtin.package:
        name: rsyslog
        state: present

  roles:
    - role: rsyslog
      tags: [rsyslog, logging, configuration]

  post_tasks:
    - name: Verify rsyslog service is running
      ansible.builtin.service:
        name: rsyslog
        state: started
      register: rsyslog_running

    - name: Display deployment status
      ansible.builtin.debug:
        msg: "rsyslog deployed successfully and running: {{ rsyslog_running.state == 'started' }}"
