---
- name: Create users for Flask validator and NGINX server
  hosts: "{{ target_hosts | default(env) | default('prod') }}"
  become: true

  pre_tasks:
    - name: Include environment-specific variables
      ansible.builtin.include_vars: "../environments/{{ env | default('prod') }}.yml"
      tags: [always]

    - name: Display selected environment
      ansible.builtin.debug:
        msg: "Setting up users for {{ env | default('prod') }} environment on {{ inventory_hostname }}"
      tags: [always]

  tasks:
    - name: Create validator group
      ansible.builtin.group:
        name: "{{ validator_group }}"
        state: present

    - name: Create validator user
      ansible.builtin.user:
        name: "{{ validator_user }}"
        group: "{{ validator_group }}"
        shell: /usr/sbin/nologin
        create_home: false
        system: true
        state: present

    - name: Create nginx group
      ansible.builtin.group:
        name: "{{ nginx_group }}"
        state: present

    - name: Create nginx user
      ansible.builtin.user:
        name: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        shell: /usr/sbin/nologin
        create_home: false
        system: true
        state: present
